#Multigpu
_target_: src.scripts.predict.Predictor
model: ${model}
trainer: ${trainer}
model_checkpoint: ${paths.output_dir}/checkpoints/final_model.ckpt

predictData:
  _target_: "src.datamodule.FullPredictDM.PatchPredictionDataModule"  # Path to the DataModule class
  image_dir: ${paths.data_dir}/Test
  batch_size: 4
  num_workers: 4

