mlflow:
  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: ${name}
  tracking_uri: null
  tags: null
  save_dir: "${paths.output_dir}/mlruns"
  prefix: ""
  artifact_location: null
