tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  name: ${name}
  save_dir: "${paths.output_dir}/tensorboard"
  version: null
  log_graph: False
  default_hp_metric: False
  prefix: ""
