_target_: src.datamodule.datamodule.BrainSectionDataModule
batch_size: ${batch_size} #128
num_workers: ${num_workers} #8
pin_memory: True

dataset:
  image_dir: "${paths.data_dir}/Images"
  mask_dir: "${paths.data_dir}/Masks"
  val_size: 0.15  # 15% of data for validation
  test_size: 0.1  # 10% of data for testing
  patch_size: ${patch_size} #128
  overlap: ${overlap} #0.5

transform:
  _target_: src.transforms.transform.trainTransform
  enable: false
  flip: true
  affine:
    scale: [0.9, 1.1]
    rotate: [-30, 30]
    translate_percent: [-0.05, 0.05]
    shear: [-0.2, 0.2]
    interpolation: "INTER_LINEAR"
  #clahe: 0.3
  #gauss_noise:
  #  std_range : [0.2, 0.44]
  #  mean_range : [0.0, 0.0]
  #  per_channel : True
  #  noise_scale_factor : 0.5
  #  p: 0.5
  #elasticTransform: 
  # alpha: 1.0
  #  sigma: 10
  #  p: 0.5
  #rCrop: 
  #  height: 64
  #  weight: 64
  #  p: 0.5


